nomenclature = {
    "Animal Husbandry": "AH",
    "Agri Inputs": "AI",
    "Agricultural Machineries": "AM",
    "Other Agri Services": "AS",
    "Consultancy Services": "CS",
    "Innovative Farmers": "IF",
    "Irrigation Systems": "IS",
    "Organic Nutrients, Inputs & Services": "OS",
    "Organizations": "OZ",
    "Plant Nurseries": "PN",
    "Seeds, Fertilizers & Micronutrients": "",
    "Chemical Pesticides & Herbicides": "",
    "Growth Regulators & Hormones": "",
    "Soluble Fertilizers & Foliar Sprays": "",
    "Soil Amendments & Reclaimers": "",
    "Seed Treatment & Storage Chemical": "",
    "Brush Cutters & Rotary Tillers": "",
    "Handheld Power Tools & Sprayers": "",
    "Garden Machineries": "",
    "Handheld Tools & Implements": "",
    "Tractor Drawn Implements": "",
    "Harvesting & Post-harvest Machines": "",
    "Country Chicken & Rural Birds": "",
    "Goat, Sheep & Pigs": "",
    "Dairy Animals – Cows & Buffalos": "",
    "Indian Breed Cows & Gov Shalas": "",
    "Animal Feeds & Veterinary Services": "",
    "Feed Supplements & Medicines": "",
    "Landscape & Gardening": "",
    "Pomegranate & Grape Cultivation": "",
    "Floriculture & Terrace Gardening": "",
    "Project Reports & Finance": "",
    "Food Processing & Exports": "",
    "Rainwater Harvesting & Recharge": "",
    "Expert Farmers Of Horticulture Crop": "",
    "Expert Farmers Of Plantation Crops": "",
    "Experts Of Minimal Processing": "",
    "Experts Of Integrated Farming": "",
    "Organic Farming Expert Farmers": "",
    "Dairy, Goat, Sheep & Poultry Farms": "",
    "Drip Irrigation Systems & Fittings": "",
    "Sprinklers, Foggers, Misters": "",
    "PVC Pipes & Fittings": "",
    "Monoblock & Submersible Pump": "",
    "Auto Switchers & Control Valves": "",
    "Solar Pumps & Lighting": "",
    "Organic Manures": "",
    "Biofertilizers & Composters": "",
    "Biopesticides, NPV, BT, Trichoderma": "",
    "Plant Growth Regulators": "",
    "Organic – Training & Consultancy": "",
    "Organic Certification": "",
    "Universities Of Agri, Horti & AH": "",
    "Krushi Vignana Kendras": "",
    "Central Research Organisations": "",
    "NGOs Working On Agriculture & RD": "",
    "State Depts. Of Agri, Horti, Seri, AH": "",
    "Training Institutes – State & Central": "",
    "Poly House & Shade House": "",
    "ASTRA Dryer & Poly Tunnel Dryer": "",
    "Electric Fence & Regular Fencing": "",
    "Birds & Wild Animal Chasing Device": "",
    "Aluminium Ladders, Climbers": "",
    "Mulch Sheets & Tarpaulins": "",
    "Fruit & Forest Plants": "",
    "Plantation Crop Plants": "",
    "Flowering & Ornamental Plants": "",
    "Bonsai & Indoor Plants": "",
    "Vegetable Nursery": "",
    "Terrace Gardening & Landscaping": "",
}
