export const nomenclature = {
  '/': 'cat',
  'Animal Husbandry': 'AH',
  'Agricultural Machineries': 'AM',
  'Other Agri Services': 'AS',
  'Consultancy Services': 'CS',
  'Innovative Farmers': 'IF',
  'Irrigation Systems': 'IS',
  'Organic Inputs & Services': 'OS',
  Organizations: 'OZ',
  'Plant Nurseries': 'PN',
  Fertilizers: 'FZ',
  Seeds: 'SD',
  Pesticides: 'PD',
  'Gou Shala for Indian Cow Breeds': 'AH-GS',
  'State Agricultural Universities': 'OZ-UAS',
  'National Institutes': 'OZ-NI',
  'Karnataka State Organisations & Departments': 'OZ-KST',
  'Non-Governmental Organisations (NGOs)': 'OZ-NGO',
  'Media Organisations': 'OZ-MED',
};
export const rnom = {
  cat: '',
  AH: 'Animal Husbandry',
  AM: 'Agricultural Machineries',
  AS: 'Other Agri Services',
  CS: 'Consultancy Services',
  IF: 'Innovative Farmers',
  IS: 'Irrigation Systems',
  OS: 'Organic Inputs & Services',
  OZ: 'Organizations',
  PN: 'Plant Nurseries',
  FZ: 'Fertilizers',
  SD: 'Seeds',
  PD: 'Pesticides',
  'AH-GS': 'Gou Shala for Indian Cow Breeds',
  'OZ-UAS': 'State Agricultural Universities',
  'OZ-NI': 'National Institutes',
  'OZ-KST': 'Karnataka State Organisations & Departments',
  'OZ-NGO': 'Non-Governmental Organisations (NGOs)',
  'OZ-MED': 'Media Organisations',
};
export default nomenclature;
