export const nomenclature = {
  '/': 'CAT',
  'Animal Husbandry': 'AH',
  'Gou Shala for Indian Cow Breeds': 'AH-GS',
  'Sheep, Goat, Rabbit, Pig and Fish Farms': 'AH-SG',
  'Poultry and Rural Birds': 'AH-PL',
  'Cow and Buffalo Dairy': 'AH-CB',
  'Dairy Machinery & Technology': 'AH-DM',
  'Agriculture Machineries': 'AM',
  'Other Agri Services': 'AS',
  'Consultancy Services': 'CS',
  Fertilizers: 'FZ',
  'General Utility Technologies': 'GU',
  'Innovative Farmers': 'IF',
  'Irrigation Systems': 'IS',
  'Organic Inputs & Services': 'OS',
  Organisations: 'OZ',
  'State Agricultural Universities': 'OZ-UAS',
  'National Institutes': 'OZ-NI',
  'Karnataka State Organisations & Departments': 'OZ-KST',
  'Non-Governmental Organisations (NGOs)': 'OZ-NGO',
  'Media Organisations': 'OZ-MED',
  Pesticides: 'PD',
  'Plant Nurseries & TC Labs': 'PN',
  Seeds: 'SD',
};

export const rnom = {
  CAT: '',
  AH: 'Animal Husbandry',
  'AH-GS': 'Gou Shala for Indian Cow Breeds',
  'AH-SG': 'Sheep, Goat, Rabbit, Pig and Fish Farms',
  'AH-PL': 'Poultry and Rural Birds',
  'AH-CB': 'Cow and Buffalo Dairy',
  'AH-DM': 'Dairy Machinery & Technology',
  AM: 'Agriculture Machineries',
  AS: 'Other Agri Services',
  CS: 'Consultancy Services',
  FZ: 'Fertilizers',
  GU: 'General Utility Technologies',
  IF: 'Innovative Farmers',
  IS: 'Irrigation Systems',
  OS: 'Organic Inputs & Services',
  OZ: 'Organisations',
  'OZ-UAS': 'State Agricultural Universities',
  'OZ-NI': 'National Institutes',
  'OZ-KST': 'Karnataka State Organisations & Departments',
  'OZ-NGO': 'Non-Governmental Organisations (NGOs)',
  'OZ-MED': 'Media Organisations',
  PD: 'Pesticides',
  PN: 'Plant Nurseries & TC Labs',
  SD: 'Seeds',
};
export default rnom;
