nomenclature = {
    "Animal Husbandry": "AH",
    "Agri Inputs": "AI",
    "Agricultural Machineries": "AM",
    "Other Agri Services": "AS",
    "Consultancy Services": "CS",
    "Innovative Farmers": "IF",
    "Irrigation Systems": "IS",
    "Organic Inputs & Services": "OS",
    "Organizations": "OZ",
    "Plant Nurseries": "PN",
    "Gou Shala for Indian Cow Breeds": "AH-GS",
    "State Agricultural Universities": "OZ-UAS",
    "National Institutes": "OZ-NI",
    "Karnataka State Organisations & Departments": "OZ-KST",
    "Non-Governmental Organisations (NGOs)": "OZ-NGO"
}
# "cat-1": "Agricultural Machineries",
# "cat-2": "Organic Inputs & Services ",
# "cat-3": "Organizations ",
# "cat-4": "Innovative Farmers ",
# "cat-5": "Plant Nurseries ",
# "cat-6": "Irrigation Systems ",
# "cat-7": "Consultancy Services ",
# "cat-8": "Other Agri Services ",
# "cat-9": "Animal Husbandry ",
# "cat-10": "Agri Inputs",
