nomenclature = {
    '/': 'cat',
    'Animal Husbandry': 'AH',
    'Agricultural Machineries': 'AM',
    'Other Agri Services': 'AS',
    'Consultancy Services': 'CS',
    'Innovative Farmers': 'IF',
    'Irrigation Systems': 'IS',
    'Organic Inputs & Services': 'OS',
    'Organizations': 'OZ',
    'Plant Nurseries': 'PN',
    'Fertilizers': 'FZ',
    'Seeds': 'SD',
    'Pesticides': 'PD',
    'Gou Shala for Indian Cow Breeds': 'AH-GS',
    'State Agricultural Universities': 'OZ-UAS',
    'National Institutes': 'OZ-NI',
    'Karnataka State Organisations & Departments': 'OZ-KST',
    'Non-Governmental Organisations': 'OZ-NGO',
}
